### ISSUE TITLE
Design Multipart helper to stream by default

### ISSUE THREAD

**Issue by sethmlarson** [encode/httpx#114]
This is a frequent problem with urllib3 in that the default behavior loads all of the file's data into memory at once before sending resulting in a huge files getting loaded into memory.

It's a hard problem to fix in urllib3 because of how the API was designed, but we can still fix our implementation not to do this.  I've got part of a patch for this currently.

**Comment by tomchristie** [comment]
Yup, defo.

One subtlety here is that right now we either support the request content being bytes or a byte iterator. The iterator case *can't* support body-preserving redirects. So we've actually got a precursor to this issue of supporting a rewindable/seekable type. (To allow rewinding back to the start of the upload.)

**Comment by sethmlarson** [comment]
Yeah there's some bits and pieces I can lift from urllib3 and some unmerged branches for that specific case.  Effectively we add support for passing a seekable object as `data` and then we implement an file-like interface for the multipart data and internally can rewind the individual file objects.

Would something like this be effective?

**Comment by florimondmanca** [comment]
Any updated context on this given where we're at now? Is this still an issue/is it easier to tackle, and how?

**Comment by tomchristie** [comment]
Ah yes. Streaming multipart would be a *great* feature for us to add now, in particular because it doesn't add any new API surface area at all, and the content streams are designed to allow us to support it. 😃

Right now we generate the multipart data on `__init__`... https://github.com/encode/httpx/blob/6e40c1b26ac3526bfe4115c00c028899d37e551e/httpx/_content_streams.py#L272-L288

Instead we should be moving that into `__iter__`... https://github.com/encode/httpx/blob/6e40c1b26ac3526bfe4115c00c028899d37e551e/httpx/_content_streams.py#L308-L309

...and `__aiter__`... https://github.com/encode/httpx/blob/6e40c1b26ac3526bfe4115c00c028899d37e551e/httpx/_content_streams.py#L311-L312

Additionally we'd want `FileField.render_data` to read and return chunks-at-a-time, and be called multiple times, rather than being called once and returning the entire file content.

**Comment by florimondmanca** [comment]
Okay — looking into it. :-) The bits around estimating the content length without reading the entire data are interesting!
