### ISSUE TITLE
On Sphinx vs. MkDocs

### ISSUE THREAD

**Issue by tomchristie** [encode/httpx#1220]
Since we're iterating nicely towards 1.0, I wanted to just open the doors to a conversation that I've not made a lot of time for in the past.

What does the community prefer wrt. Sphinx vs. MkDocs for our documentation?

In the past my view has been "hey let's keep things consistent across encode, and use MkDocs for HTTPX". But perhaps it's worth having an open conversation about this? Not to say that we *should* switch or anything, but it's worth us being open to it, and it'd be interesting to have a look at the differences if someone was keen on pulling together a PR switching things over to Sphinx + RST.

Some thoughts...

* I think the MkDocs theme is really nice, and it's easier to theme.
* The API docs support in MkDocs isn't great, although we can improve that somewhat.
* There's no versioned docs support in MkDocs, and it's not likely to happen anytime soon.
* Probably marginally nicer to write in Markdown over RST (better tooling etc) but that's not really an end-user issue.

Useful for comparison...

* [Requests Docs](https://requests.readthedocs.io/en/master/) (Sphinx, Alabaster theme)
* [HTTPX Docs](https://www.python-httpx.org/) (MkDocs, Material theme)

Happy to also take a simple emoji polling on this to help inform any decisions here...

🚀 - Prefer MkDocs overall
❤️ - Prefer Sphinx overall.

Also see https://twitter.com/_tomchristie/status/1298564672354951174

**Comment by florimondmanca** [comment]
I think the API docs support is a rather strong contender in favor of Sphinx. It's really great being able to walk through all the details of a library, with links to source code, without having to dig into the source code ourselves.

There are actually a few nice projects that would make usage of Sphinx at least competitive with MkDocs…

- Material for Sphinx: https://bashtage.github.io/sphinx-material/
- MyST - Markdown for Sphinx: https://myst-parser.readthedocs.io/en/latest/

These could solve the two minus points against Sphinx (MkDocs Material theme, and Markdown support), leaving us with only bonus points compared to MkDocs (great API docs support, versioning, similarly rich ecosystem of extensions, etc).

**Comment by euri10** [comment]
Sphinx ❣️

**Comment by n2ygk** [comment]
Sphinx also supports [inter-sphinx links](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html) which I would love to use when linking to upstream projects like DRF from downstreams like [DJA](https://django-rest-framework-json-api.readthedocs.io/) or my own further downstream projects.

**Comment by StephenBrown2** [comment]
On API docs, https://github.com/pawamoy/mkdocstrings/ is a fantastic solution that works really well (quite similar to Sphinx autodoc), though it wouldn't support inter-sphinx links.

That said, Sphinx has come a long way and even supports type-hinted annotations now, so it might be worth a shot, especially with MyST as a thing.

**Comment by pradyunsg** [comment]
> There are actually a few nice projects that would make usage of Sphinx at least competitive with MkDocs…

In the area of [Sphinx Themes](https://github.com/sphinx-themes/sphinx-themes.org), I'd like to flag a fairly recent development: [Furo](https://pradyunsg.me/furo/contributing/). It's supposed to be a Sphinx theme that's nice out-of-the-box while also being easy to customize extensively. I think it looks pretty good; although given that I'm the author, I'm definitely biased. ;)

It's a WIP<sup>*</sup> right now. OTOH, it was recently adopted by [urllib3](https://urllib3.readthedocs.io/en/latest/) as part of their documentation overhaul. Obviously, I'm planning to switch the documentation of a few of the projects I maintain to switch over to it once the stable release is made.

> [regarding myst-parser] Has anyone got experience with that?

I'd strongly recommend using myst-parser, since IMO it does a really good job of blending markdown with all of Sphinx's directives with a pretty-neat syntax. It's basically as capable as reStructuredText for anything reasonable that I have tried to do. I've been using it for writing [Furo's documentation](https://github.com/pradyunsg/furo/tree/master/docs/), seen it being used in Sphinx Book Theme's documentation for [inline Jupyter Notebooks (!)](https://sphinx-book-theme.readthedocs.io/en/latest/notebooks.html).

---

<sup>*</sup>It's 80% done IMO, with the main missing pieces being that the API-docs stuff needs tweaking to look better and I need to properly flesh out the user facing documentation for the theme.

**Comment by hynek** [comment]
I think theming (→ Furo) and Markdown (→ MyST) should be kept  out of the discussion so here's a bunch of practical reasons why – as a **user** – I'm not a fan of projects using MkDocs:

- I know you should end with the most important one, but I'll start with it because it's very dear to my heart: MkDocs has no concept of a machine-readable API information. As someone who can't write code without looking up APIs all the time this is very frustrating.

  My productivity depends on having an (offline!) API browser like [Zeal](https://zealdocs.org) (free, cross-platform) or [Dash](https://kapeli.com/dash) (paid, macOS-only) one keystroke away. I love it so much that I even wrote doc2dash for converting Sphinx' `objects.inv` to them (they use the same format).
- Intersphinx links are a great quality of life improvement when I can link easily between API definitions even between projects hosted on different sites. httpx's docs are full of "See X" which really should be links and not left to the user to find. So even if I'm on the page, the docs feel tacked on
- Versioned docs aren't a big deal to me but can be crucial for a project that is moving fast.

There's also a lot of features in Sphinx you might not be aware of, that would improve _your_ life. Like the recently-ish added [support for types](https://tk0miya.hatenablog.com/entry/2020/02/09/190523).

**Comment by tomchristie** [comment]
@hynek I hear ya on that for sure.

When I first asked this question I think I was partly hoping that there'd be an overwhelming preference towards Sphinx, because that would at least make things more simple.

The lack of good interlinking is something that could potentially be addressed in MkDocs, or adequately worked through with a well-done plugin, but also I'm absolutely not against us migrating to Sphinx.

**Comment by hynek** [comment]
> When I first asked this question I think I was partly hoping that there'd be an overwhelming preference towards Sphinx, because that would at least make things more simple.

I'm happy to be proven wrong, but I suspect that the support for MkDocs overwhelming stems from Markdown. Maybe the looks of the theme coming second. 🤔 My experience in these kinds of discussions is that people usually a) don't know about myST and b) don't know about Sphinx's many upsides. 😐

All that to say: take the voting result with a grain of salt. :)

**Comment by florimondmanca** [comment]
Quite agree that the emoji poll on this issue description should be considered as mostly irrelevant, since there are various reasons why people may prefer either (eg: being "used to it"), not all of which apply to _us_ choosing between the two options. :-)

**Comment by n2ygk** [comment]
Changing my tune here after being "forced" to convert my Sphinx docs to Mkdocs as I was experimenting with [backstage](https://backstage.io) techdocs (which uses mkdocs):
- It was super easy to convert, because, even though I was using Sphinx, my pages were all markdown. Clearly if this were heavy RsT it would have been more work.
- Using the [macros](https://mkdocs-macros-plugin.readthedocs.io/) plugin I was even able to dynamically determine the git repo (and flavor) by adding a small `define_env()` that parses the remote out of .git/config.
- Still working through issues getting `mkdocstrings` to generate API docs ("mkdocstrings.handlers.CollectionError: 'ResourceRelatedField' object has no attribute 'metadata'"). And of course since my docstrings are written with RsT they won't "just work".


It would still be nice to have the equivalent of inter-Sphinx links.

**Comment by pawamoy** [comment]
> It would still be nice to have the equivalent of inter-Sphinx links.

I'm definitely going to implement this :slightly_smiling_face: In the next few days I'll open a Feature Roadmap issue to replace to README roadmap. "Inter-sphinx"-like feature will be one of them. With [sphobjinv](https://github.com/bskinn/sphobjinv) I think mkdocstrings/pytkdocs will be able to support current Sphinx objects inventories. It will take some time of course. Quite the bugs to fix as well :sweat_smile: So much to work to do :grin:!
