### ISSUE TITLE
Get ride of one result when getting both 80 and 443

### ISSUE THREAD

**Issue by marcelo321** [encode/httpx#1235]
Hello,

Would it be possible to get ride, for example, of port 80 if both 80 and 443 are open?

lets say we get this results:

```
hackerone.com:80
hackerone.com:443
hackerone.com:4444
hackerone.com:8081
```

Since most of the times, 80 just redirects to 443 (if there is https), I want to just get this results if both 80 and 443 are open:

```
hackerone.com:443
hackerone.com:4444
hackerone.com:8081
```

I can't do it in bash and I have no idea how to do it, so I am asking the cool devs of this tool if they can add it or have a tip on how to do it? Maybe add a flag like httprobe has: `--prefer-https`?

**Comment by florimondmanca** [comment]
Hi,

Please try and follow issue templates - they would have hinted you at posting this kind of usage question on our chat over at https://gitter.im/encode/community.

That being said, I'm not sure I understand what you're trying to do, or why you're not able to do it. If you're asking "does HTTPX support HSTS" (that is, honoring that a server prefers to be requested via HTTPS), then the answer is "no since 0.14, but we're potentially open to adding it again as a new flag". Otherwise, if you have knowledge about which ports are available on a server, then you can probably implement the logic you're asking about here in plain Python code...?

Anyhow, closing for now, feel free to reach out to the chat with some more details about your use case if you remain blocked. Thanks!

**Comment by marcelo321** [comment]
Yes I just wanted to know if a flag similar to --prefer-https like httprobe has could be implemented. If both 80 and 443 are open on the same host, to just store the 443. Anyway, it might be too much trouble to do it so it's all cool.
