### ISSUE TITLE
Add `httpx.MockTransport()`

### ISSUE THREAD

**Issue by tomchristie** [encode/httpx#1303]
Based on https://github.com/encode/httpx/blob/8ceb34f48672f89de2458df371e2624659e2c24f/tests/utils.py#L27-L75

Usage:

```python
def handler(request: httpx.Request) -> httpx.Response:
    return httpx.Response(200, json={"hello": "world"})


client = httpx.Client(transport=httpx.MockTransport(handler))
```

Since #1297 and #1293 we're almost at the point where we can have a really nice simple `httpx.MockTransport(handler=...)` implementation, which I think would be worthwhile, given how useful we find it in our own tests, and how it'd help round out the usefulness of the Transport API to our users (and provide a point of demonstration around being able to use `Request`/`Response` models in that context.)

~~The one outstanding bit of work that we still need really is the `.request`+`.arequest` refactoring mentioned in https://github.com/encode/httpx/issues/1274~~

Also worth mentioning that the following all fit together as as a nice related set of enhancements...

* Mount API - #977
* `httpx.HTTPTransport()` - #1302
* `httpx.MockTransport()` - This PR.

So it's *possible* that we ought to aim to release them together, just to bring some extra coherence to eg. "Here's the mount API we've just added, and here's the sort of stuff you can do with it"

**Comment by lundberg** [comment]
I like your thoughts @tomchristie !

If I read this correctly, the current [RESPX](https://github.com/lundberg/respx/) `MockTransport` could get rid of `mock` patching `httpcore` transports, and instead be refactored to a *pattern > response* handler.

Though, I still think `mock.patch` functionality would be of interest in RESPX to be able to mock `httpcore` individually, so that future libs using `httpcore` still can use RESPX for mocking.
