### ISSUE TITLE
ResponseNotRead raises since v.0.15.0

### ISSUE THREAD

**Issue by igolkotek** [encode/httpx#1323]
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.

### Describe the bug
Response behaviour has been changed since 0.15.0, so that calling json() on response instance raises ResponseNotRead exception.

### To reproduce
import httpx
r = httpx.Response(200, content='content')
result = r.json()

### Expected behavior
result = 'content'

### Actual behavior
httpx.ResponseNotRead: Attempted to access response content, without having called `read()` after a streaming response.

### Environment

- OS: Linux
- Python version:  3.8.2
- HTTPX version: 0.15.3
- Async environment: asyncio
- HTTP proxy: no
- Custom certificates: no

**Comment by tomchristie** [comment]
Thanks for raising this, yup.
Resolved in #1324 

Note that since 0.15.0 you can also use `text=...`, `html=...` and `json=...` when creating response instances directly.
We'll probably have a new minor release very soon resolving this for you, but in the meantime you could use `text=...` which won't trigger the bug, or use `content=<bytes>` which again, won't trigger the bug.
