### ISSUE TITLE
Help running tests during debian package build

### ISSUE THREAD

**Issue by sandrotosi** [encode/httpx#1370]
Hello,
when debian builds a package, we prevent access to the internet (due to security/privacy as well as reproducibility reasons), this also applies when running tests.

In the specific case of httpx, the test suite spins up 2 services listening on port 8000 and 8001; while i can set `http_proxy=120.0.01:8000` this means the tests accessing the service on port 8001 will fail (and vice versa if i switch the ports).

Do you think there's a clever way for me to run tests? i was thinking something as simple as:

1. set `http_proxy=120.0.01:8000` and run the test suite skipping the tests accessing localhost:8001
2. set `http_proxy=120.0.01:8001` and run the test suite skipping the tests accessing localhost:8000

but i'm not sure how to identify those tests and/or if they can be skipped at all.

I hope you may provide some insight into this issue.

Thanks in advance,
Sandro

**Comment by florimondmanca** [comment]
@sandrotosi Hi,

So I understand your test suite policy won't allow tests to access even the local network? Is there some kind of allow-list behavior you could use to allow the HTTPX test suite to request `localhost:8000`/`localhost:8001`?

Otherwise, I can't really think of clever hacks, no. I'm not sure how we'd be able to do otherwise, given that we use those local servers for E2E testing (making sure HTTPX plays well with a real server), and I don't think there's a simple way to run those in-memory (without some clever patching of `socket` that I don't think we want to tip our toes into).

Closing because I think this should answer your question… I think allowing those two specific ports would be your best bet. If the Debian build policy still disallows that, you may be to do some pytest fixture overriding magic (eg override the `server` fixture so it calls `pytest.skip()`).

**Comment by tomchristie** [comment]
Aside: I'd be super okay with us switching out those tests to use a local server, if anyone wants to take that on. 😀

**Comment by florimondmanca** [comment]
@tomchristie Well, doesn't our test quite _already_ use local servers? Or do you mean, a local server not spun up from Python (but eg started via an external script)?
