### ISSUE TITLE
Add request and response properties to Exceptions

### ISSUE THREAD

**Issue by RRMoelker** [encode/httpx#141]
In order to gracefully handle different HttpErrors I would like to know the url and status code of the offending call. Currently I'm wrapping the httpx `raise_for_status` code so this is added. However I think this would be a good addition to the core HttpError exception.

So an HttpError would consist of:
* message
* status code
* url

A drawback is that these additional properties may grow unwieldy as more exception handling cases are discovered. But I think some basic call information is called for.

**Comment by tomchristie** [comment]
One of the intents of `httpx` is to provide a broadly requests-compatible API - so looking towards what requests provides on exceptions is a good first pass here.

Sensible their base exceptions allow for `request` and `response` arguments, which is pretty much what we should do too.

> these additional properties may grow unwieldy

`request` and `response` would presumably be sufficient here - since we can access `url`, `status_code` or whatever else.

**Comment by RRMoelker** [comment]
Agreed... Much cleaner solution.

For reference:
* https://2.python-requests.org/en/master/_modules/requests/exceptions/
* https://2.python-requests.org/projects/3/user/quickstart/#errors-and-exceptions

**Comment by halbow** [comment]
I'd like to take a look on this if @RRMoelker is not already implementing a solution !

**Comment by RRMoelker** [comment]
Not working on a solution @halbow. So please
