### ISSUE TITLE
NETRC is missing from the Environment Variables docs

### ISSUE THREAD

**Issue by florimondmanca** [encode/httpx#1417]
After reading through the docs section on [NETRC support](https://www.python-httpx.org/advanced/#netrc-support), we happen to support passing the NETRC file location via a `NETRC` environment variable. But this is not documented in [Environment Variables](https://www.python-httpx.org/environment_variables/), so let's add it there.

**Comment by meist0731** [comment]
Hi, I'm a newcomer here. I would like to contribute to this issue :D  
I noticed the environment variable still hasn't added there. Could I have a try?

**Comment by johtso** [comment]
@meist0731 go for it!

**Comment by Vibhu-Agarwal** [comment]
May I take up this issue?

**Comment by meist0731** [comment]
> May I take up this issue?

Hey, I'm already working on it these days. If you also wanna take it, it's my honor if you could collaborate with me together.  later on, I will share the material I found useful and my ideas about it here.  :D

**Comment by meist0731** [comment]
Hi guys :D,  @Vibhu-Agarwal @johtso when I wrote the example to the .netrc environment variable doc,  I just applied the method of changing the .netrc environment by OS module into the example script directly, instead of setting this environment variable in the console with "netrc = 'path/my_netrc python -c ..." , cuz it appears a little bit long in the console. How do you think if it is proper or not? 

Another thing, I've sent the first pull request  :DDD, but it says "First-time contributors need a maintainer to approve running workflows".  Would you mind approving to run the workflow? Thank you😊

**Comment by tomchristie** [comment]
This was resolved in https://github.com/encode/httpx/pull/1675

Thanks @Mayst0731!
