### ISSUE TITLE
httpx.ConnectError: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1076)

### ISSUE THREAD

**Issue by dingyxyx** [encode/httpx#1429]
import httpx
import ssl
#

headers = {
"Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
"Accept-Encoding": "gzip, deflate, br",
"Accept-Language": "zh-CN,zh;q=0.9",
"Cache-Control": "max-age=0",
"Connection": "keep-alive",
"Cookie": ".ASPXANONYMOUS=sH1Gv5gI1wEkAAAAYmE2NDVhMTQtY2I3MC00MzM1LWEwYzEtNjkwNmRiMDZkZGRl0; ASP.NET_SessionId=52s4huldvl4jgug21snxqzx2; language=zh-CN; DotNetNukeAnonymous=33e00f46-c193-48c8-9669-6e58606081be",
"Host": "www.csgc.com.cn",
"Sec-Fetch-Dest": "document",
"Sec-Fetch-Mode": "navigate",
"Sec-Fetch-Site": "none",
"Sec-Fetch-User": "?1",
"Upgrade-Insecure-Requests": "1",
"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
}
response = httpx.get("https://www.csgc.com.cn/1077.html",verify=False,headers=headers).text
print(response )

![image](https://user-images.githubusercontent.com/76154396/102466323-d731e280-4089-11eb-8576-618c76c858f8.png)

**Comment by dingyxyx** [comment]
Why does SSL exist? I'm already verify=False

**Comment by dingyxyx** [comment]
Why does SSL exist? I'm already verify=False @davidbgk @Singletoned @simonw @xrmx

**Comment by florimondmanca** [comment]
@dingyxyx Hello,

Not appropriate at all to tag people on this thread without letting time for some folks to do an initial assessment (like I'm doing) — especially since I doubt the folks you've tagged are immediately related to the issue you're encountering, or HTTPX altogether. You need to be mindful of people's time — and right now I'm feeling frustrated that I have to apologize to them of these unnecessary ping.

Besides, we have a proper issue template in place that's meant for people to give basic information about their environment setup, and help them do an initial analysis of what could be happening. Please follow it — "help us help you".

Thanks.
