### ISSUE TITLE
Are there any plans to support GraphQL

### ISSUE THREAD

**Issue by yeducom** [encode/httpx#1454]
Are there any plans to support GraphQL

**Comment by florimondmanca** [comment]
@yeducom Hello,

Hmm, off the top of my head, no, I don't think we would plan HTTPX to include any kind of built-in GraphQL functionality. HTTPX is for HTTP, and GraphQL is a layer on top of that.

If you provide some compelling arguments in favor of that then we can discuss it, otherwise I think GraphQL clients would just build on top of HTTPX if they want. (I assume existing clients use eg `requests` or `aiohttp`. Up to them to abstract the HTTP layer out so they may use HTTPX as well, I suppose.)

Thanks!

**Comment by florimondmanca** [comment]
And btw, it's already possible to use HTTPX (or any other HTTP library for that matter) as a client to request GraphQL endpoints. Like so:

```python
>>> import httpx
>>> url = "http://localhost:8000/graphql"
>>> content = "{ hello(name: 'Chuck') }"
>>> headers = {"content-type": "application/graphql"}
>>> response = httpx.get(url, content=content, headers=headers)
```

Or, with curl:

```bash
curl http://localhost:8000/graphql -d '{ hello(name: "Chuck") }' -H "Content-Type: application/graphql"
```
