### ISSUE TITLE
Tilde characters in URL paths should be treated as an unreserved character. (~)

### ISSUE THREAD

**Issue by LeBatou** [encode/httpx#1517]
### Checklist

- [X] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug

Footlocker for example doesn't accept the percent encode of the tilde, it means that you cannot request the page

### To reproduce

Burp on this page for example, you will get a 301 everytime, because they don't accept the percent encode of the tilde, you can take a look at it if you use a MITM like Charles or Burp
https://www.footlocker.pt/product/~/315345197602.html

### Expected behavior

request on this URL : https://www.footlocker.pt/product/~/315345197602.html
(MITM on chrome)

### Actual behavior

request on this URL : https://www.footlocker.pt/product/%2F/315345197602.html
(MITM on httpx)

### Debugging material

Any MITM software

### Environment

- OS: Windows
- Python version: 3.8.5
- HTTPX version: 0.17.1
- Async environment: N/A
- HTTP proxy: no
- Custom certificates: no

**Comment by LeBatou** [comment]
Ok I did some research, and the rfc3986 module has been updated for this problem on github but not in pip, everything is working while loading the new rfc3986 manually.

**Comment by tomchristie** [comment]
@LeBatou Great thanks!

Referenced issue is https://github.com/python-hyper/rfc3986/pull/74

We might want to check in with the rfc3986 team and see what we can do about:

* Helping get the test suite passing again on that repo.
* Any help we can provide in order to get a release rolled.

(Clearly there's also some longer term thinking to do about how we can try to build on our sponsor model to help downstream projects too.)
