### ISSUE TITLE
use uvloop as event loop provider.

### ISSUE THREAD

**Issue by cansarigol** [encode/httpx#158]
Should we use uvloop as event loop provider? I couldn't find any discussion about this and I'm wondering that what you are thinking of using uvloop?

**Comment by yeraydiazdiaz** [comment]
I believe the point is for the user choose their concurrency framework and have `httpx` adapt to it, which would extend to the choice of event loop implementation.

**Comment by cansarigol** [comment]
you're right but event loop of `asyncio` is already used in project hence I thought that we can use `uvloop` and nothing changes, just increases the performance.

From doc: 
"uvloop implements the asyncio.AbstractEventLoop interface which means that it provides a drop-in replacement of the asyncio event loop."

**Comment by yeraydiazdiaz** [comment]
Sure, I'm just saying that we should not *impose* `uvloop` on the user by making it a requirement of `httpx`.

If they can't or won't use `uvloop` they should be free to do so, in the same way that if they choose to use trio instead of asyncio.

Of course this is just my opinion 🙂

**Comment by yeraydiazdiaz** [comment]
Unless I'm misunderstaning and you mean using `uvloop` in development?

**Comment by cansarigol** [comment]
> Unless I'm misunderstaning and you mean using `uvloop` in development?

I mean using in production.

**Comment by cansarigol** [comment]
> Sure, I'm just saying that we should not _impose_ `uvloop` on the user by making it a requirement of `httpx`.
> 
> If they can't or won't use `uvloop` they should be free to do so, in the same way that if they choose to use trio instead of asyncio.
> 
> Of course this is just my opinion 🙂

if using uvloop makes sense, maybe we can add "use uvloop" feature with a parameter and document it?

**Comment by tomchristie** [comment]
This shouldn’t really be in-scope for httpx. Switching to uvloop might be a reasonable thing to do in certain very high throughput scenarios, but there’s no need for us to couple this package to uvloop. Users can just set the event loop policy explicitly if that’s what they need.

In a typical case, you’ll often be running within the context of a web server, such as uvicorn, which is a more appropriate place to control settings such as the event loop policy.

Possible that we could document and point to uvloop, but I’m probably lukewarm on that, since in most scenarios httpx is used its not going to be relevant anyways.

(Would need to something that’s topping out on throughput, but not in a webserver that’s already selecting the best available policy)

**Comment by cansarigol** [comment]
Ok thanks, I got the logic.
