### ISSUE TITLE
Raise an exception when incorrect type is passed to `auth`.

### ISSUE THREAD

**Issue by tomchristie** [encode/httpx#1852]
We might well want to do some strict type checking on the `auth=...` argument, because more than once we've had reports from users who have been trying to use a `requests` authentication class with `httpx` and wondering why things were not working.

See discussion https://github.com/encode/httpx/discussions/1847

**Comment by janheindejong** [comment]
I think the difficulty is that the `auth` argument can be of the following types: 

https://github.com/encode/httpx/blob/82ba15b52189eacec74f2ec7dbd81f3c70a69261/httpx/_types.py#L72-L77

Here the callable should take and return a `httpx._models.Requests` instance. I don't know of a way to check for inputs and outputs of a function without executing it, and that sounds rather un-Pythonic (since ducktyping is a fundamental part of Python). 

I see a few options: 

1. Add a test call to the passed callable to _build_auth or FunctionAuth.__init__, to see if it behaves like it should (e.g. pass a Request object, receive a Request object). 
2. Add typechecking to `FunctionAuth.auth_flow`; this will get called when performing a request
3.  Create and abstract "AuthCallable" with abstract `__call__`  method that needs to be subclassed

The upside of 1 and 3 are that they fail when creating the instance, not when executing. The downside of 3 is that it is a breaking change, is a bit un-Pythonic, and reduces flexibility. 

@tomchristie let me know if you have any preference or ideas, so that I can give this one a crack :-)

**Comment by tomchristie** [comment]
Right - there's really nothing we can do here (outside of changing the API so that we *don't* accept plain callables.)

We *do* check the auth type, and raise a `TypeError` on invalid types. See here...

https://github.com/encode/httpx/blob/0088253b32c7e6541ce85f40429f133c01ca35dc/httpx/_client.py#L422-L432

It's just that one of the valid argument styles is `if callable(auth)`, which we can't be checking for in any more sensible way, and which *will* catch and allow `requests` auth classes.

Perhaps we'll revisit this *sometime* much further down the line by making the API more strict in the ways that we can pass authentication classes, and not allowing the lazy `auth = some_callable` style, but for now I think we just need to close this off.
