### ISSUE TITLE
DeprecationWarning - encode_request with str data

### ISSUE THREAD

**Issue by mm0** [encode/httpx#1947]
https://github.com/encode/httpx/blob/716749e3fd3c99cb47cc20b96def280dcb3c8d16/httpx/_models.py#L1102

When a `Request` is created where `content` is `None` and `data` is a `str` a Deprecation Warning is output by this call to `_content.encode_request(`

```
httpx/_content.py:179: DeprecationWarning: Use 'content=<...>' to upload raw bytes/text content.
```

A possible solution would be to change this line to be the following:
```
            if content is None and not isinstance(data, dict) :
                content = data
                data = None
            headers, stream = encode_request(content, data, files, json)
```

**Comment by aminalaee** [comment]
Can you elaborate the point in doing this?

**Comment by florimondmanca** [comment]
Hi @mm0 

This is indeed the expected behavior -- for string content we support passing `data=...` for compatibility with Requests, but raise a DeprecationWarning to hint users at `content=...`, which is more correct.

Closing this unless this warning is raised in other unexpected situations. Thanks!
