### ISSUE TITLE
SSLContext get created unconditionally which can cause serious performance issues

### ISSUE THREAD

**Issue by kissgyorgy** [encode/httpx#2298]
### Discussed in https://github.com/encode/httpx/discussions/2245

<div type='discussions-op-text'>

<sup>Originally posted by **kissgyorgy** May 25, 2022</sup>
Our use case is that we built an API Gateway, in which we use httpx as a client to connect to the backend service.

We have a multi-tenant system, so we make a new httpx client every time to isolate customer requests completely.
We have a serious performance issue this way, we measured it, and every request takes 100ms longer just because a `ssl.SSLContext` is created unconditionally, so we spend a lot of time building `SSLContext`s, which we don't need anyway, because we don't need an HTTPS connection to the backend, as the two services are on the same machines.

I tried to solve it by passing in a global `httpx.AsyncHTTPTransport`, but httpx closes the transport after finishing the request, and I was very confused by that so I didn't thought it could be solved this way.
The next thing I tried to implement a _global connection pool_, so the `SSLContext` would be created at application startup only once, but because of a serious bug in `httpcore` about corrupted connections, we couldn't do that either (we would have hit the same bug with the global transport implementation too).

A trivial implementation would be to only create `ssl.SSLContext` in case of HTTPS connections, which [httpcore is already doing correctly](https://github.com/encode/httpcore/blob/b76afce454aa3c90bbe7f98424ff2fc8a95d45b6/httpcore/_sync/connection.py#L135-L140), but for some reason, [httpx does this unconditionally](https://github.com/encode/httpx/blob/89cdd903b2f339c6ae319773c31b8c9352bd9cd8/httpx/_transports/default.py#L126).

Another implementation idea by @vlaci that there could be an `ssl_context_factory`, which could be implemented by users.

Here is a py-spy snapshot analyzed with [speedscope](https://www.speedscope.app/), which shows we spend half the time creating unused `SSLContext`s:
![image](https://user-images.githubusercontent.com/244203/170277618-7aa207d2-8376-4102-8c69-c32ebaf77e9b.png)
</div>

**Comment by tomchristie** [comment]
I think you'd find the same behaviour here with `requests` or `urllib3`.

I'd suggest either reusing the same transport as @florimondmanca suggested in https://github.com/encode/httpx/discussions/2245. You could also just share a single ssl context by creating a global SSL context instance that you pass in to each client with `verify = ssl_context`.

For now I'd suggest we close this off, as this isn't an issue when you:

* Share a single client.
* Share a single transport across multiple clients.
* Share a single ssl context across multiple clients.

I do think there's some possible scope for improvement here, both around the API for SSL configuration, and potentially also for reusing rather than recreating SSL contexts, but at this point in time I don't think we'd want to consider either of those as being in scope.
