### ISSUE TITLE
Concurrency sub-package

### ISSUE THREAD

**Issue by florimondmanca** [encode/httpx#245]
Currently, the `concurrency.py` module is actually asyncio-specific. Preparing for alternative concurrency backend support, we should consider spinning it into a `concurrency/asyncio.py`, leaving room for backend-related stuff to go into `concurrency` package.

**Comment by tomchristie** [comment]
Yup. Let's also go for `concurrency/base.py` or `concurrency/interfaces.py` for the base interfaces, to keep things cleaner.

We *may* also want to not expose the concurrency interfaces at the top level of the `httpx` namespace, but instead end up with `httpx.concurrency.BaseSemaphore` etc... since we won't *generally* expect our user base to be implementing custom concurrency backends.

**Comment by florimondmanca** [comment]
Reopening this for the interfaces.py bit. :-)

**Comment by florimondmanca** [comment]
Actually... -> #249
