### ISSUE TITLE
Using a Client with a proxy to plain http endpoints returns 200 for the first, and 404 for any others.

### ISSUE THREAD

**Issue by JB0925** [encode/httpx#2488]
I had a discussion with @tomchristie on Gitter about an issue I am seeing with using a Client instance with a proxy when trying to send requests to multiple different plain http endpoints. The first request will return 200, and any subsequent requests to a different plain http endpoint will return 404. Our proxy's logs are showing that the requests are being handled correctly and authorized. Debugging via our proxy is not showing anything out of the ordinary, either.

Context: My team built and maintains a proxy used by other teams for various use cases. Sometimes these use cases include having to send multiple requests to plain http endpoints (web crawling, etc.). I am in the process of creating an http client for our proxy, which has several different authentication choices, etc., and am trying to wrap httpx to do so. In doing so, I noticed the above issue yesterday. I'll provide examples below.

```
with httpx.Client(proxies="http://user:pass@myproxy.net:8000") as client:
    x = client.get("http://www.google.com")
    y = client.get("http://www.facebook.com")

print(x.status_code, y.status_code)  # 200, 404
```

This happens no matter what the second request URL is. It also doesn't seem to matter how many requests you send after the first. They all return 404.

However, if I make repeated calls to the **same** http endpoint ala:

```
with httpx.Client(proxies="http://user:pass@myproxy.net:8000") as client:
    x = client.get("http://www.google.com)
    y = client.get("http://www.google.com")

print(x.status_code, y.status_code)  # 200, 200
```

It returns 200 each time.

I should also mention that this happens even if I take the authentication out of the proxy hostname and use an httpx.Proxy instance ala:

```
proxy = httpx.Proxy("http://myproxy.net:8000", auth=("user", "pass"))
with httpx.Client(proxies=proxy) as client:
    x = client.get("http://www.google.com")
    y = client.get("http://www.facebook.com")

print(x.status_code, y.status_code)  # 200, 404
```

I also cannot reproduce this behavior with the high level API.

```
x = httpx.get(url1, proxies=same_proxy)
y = httpx.get(url2, proxies=same_proxy)
print(x.status_code, y.status_code)  # 200, 200
```

Finally, using the Client **without** a proxy and sending requests to multiple different http endpoints is successful each time. Thank you for all of your hard work on this project. It is greatly appreciated.

**Comment by tomchristie** [comment]
Okay, I think I know what's going on here, but let's work it through.

First up, does this reproduce when you're using `https` URLs, or is it only for `http` URLs?

**Comment by tomchristie** [comment]
Gotcha.

Next question then, are you able to reproduce the same issue with `requests` instead of `httpx` or not?

**Comment by JB0925** [comment]
Yes, using a requests.Session() instance we get the same behavior.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tomchristie** [comment]
Okay, I believe what's happening here is to do with the connection pooling.

* For HTTPS proxies, we open a new connection (through the proxy) for every host. That's required for HTTPS proxies, because the SSL is bound to whichever host we're connecting too.
* For HTTP proxies, we only open a single connection to the proxy, which we then reuse for requests to *any* outgoing hosts. That (should be) okay, because the proxy can have a single client connection, which it then relays onto one-or-more outgoing connections.

However, if the HTTP proxy implementation only establishes a single outgoing connection which it then always re-uses, you'll end up with behaviour where the connection is established to (say) `"google.com"`, but when it's reused and a request to `"facebook.com" is issued, it's still sent on to the `"google.com"` server, which will see an invalid `Host` header, and return a `404` or other error code.

What surprises me is that I've not been able to find this issue raised against `requests` or `urllib3`, even though they (evidently) have the same connection pooling as we use here. Maybe I'm not looking closely enough.

Anyways, the best approach here would be for us to switch our behaviour so that we issue new proxy connections for each host. Being *resilient* here is more important than being efficient.

Implementation-wise, here's how we can make the fix...

The HTTPS proxy implementation will indicate that it can be re-used for any requests that are to the same remote origin...

https://github.com/encode/httpcore/blob/master/httpcore/_async/http_proxy.py#L316

By contrast, the HTTP proxy implementation will indicate that it can be re-used for *any* `http://` request...

https://github.com/encode/httpcore/blob/23cbfca76a1aaad186e8fba1baf948506446d43d/httpcore/_async/http_proxy.py#L184

We need to change that second behaviour so that it matches the first one.

**Comment by JB0925** [comment]
Got it. I see what you mean. Going to take a look at it. Thanks a bunch for looking into it so promptly, Tom.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by JB0925** [comment]
Tom, I think I have solved the issue given your advice above. I made it so that both ForwardHttpConnection and AsyncForwardHttpConnection are instantiated with a “remote_origin” attribute, just as their tunnel counterparts are. When I did that and changed the line in “can_handle_request()” to “return origin.scheme == self._remote_origin”, everything works as intended.

Is this something that you all will handle, or would you want me to submit a pull request? I don’t really have a lot of experience with open source. If you want me to make the PR, what would you want to see? A test or two? It’s only like 6 or so lines of code total.

I guess what I mean is that I don’t want to be like “well uhhh….can you just do this for me?”, but I also don’t know your process for making these changes / if you only allow certain people to do it, etc. Let me know if you want me to take any next steps, otherwise I’m happy to leave it to you all! Thanks again for being so prompt and helpful.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tomchristie** [comment]
Okey dokes. Fix over at https://github.com/encode/httpcore/pull/637
If you're able to test against that and confirm on the issue that'd be great.
Then once we've got a new release of `httpcore` out, this should be resolved for ya.

**Comment by JB0925** [comment]
Great! I’ll pull that in later this evening and confirm. Thank you so much!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by JB0925** [comment]
@tomchristie , can confirm this works. Again, thank you so much for your time and help. Quick question, is there a way to find out when a new release of `httpcore` is out? Or just keep checking back periodically? Thanks again.
