### ISSUE TITLE
Environment support

### ISSUE THREAD

**Issue by tomchristie** [encode/httpx#33]
Needs to handle anything that requests currently deals with when `trust_env=True` is set.
`.netrc`, `REQUEST_CA_BUNDLE` and anything else relevant.

First step to dealing with this would be to outline *exactly* what set of stuff `requests` includes. If anyone wants to dig into this and comment on this issue comprehensively with what set of behavior we need, then that'd be a great start.

We have `adapters/environment.py` currently stubbed out to deal with adding in this behavior.

**Comment by jtimmins-post20** [comment]
If this is still important, I'd be interested in doing some research here to determine what exactly `requests` includes, and then possibly implementing proper functionality.

**Comment by jhtimmins** [comment]
If this is still important, I'd be interested in doing some research here to determine what exactly requests includes, and then possibly implementing proper functionality.

**Comment by sethmlarson** [comment]
This is definitely important! If you can lend a hand with discovery that'd be great.

**Comment by cansarigol** [comment]
Hi, I tried to include netrc support. #177 what do you think about this approach?

**Comment by sethmlarson** [comment]
We still need a way to grab environment variables and to document those environment variables for this issue to be closed.

**Comment by florimondmanca** [comment]
I did some research in the Requests docs looking for environment variables it supports, and whether we support them already:

- [x] `NETRC`
- [ ] `REQUEST_CA_BUNDLE` (see [here](https://2.python-requests.org/en/master/user/advanced/#ssl-cert-verification))
- [ ] `HTTP_PROXY`, `HTTPS_PROXY` (see [here](https://2.python-requests.org/en/master/user/advanced/#proxies)), [`ALL_PROXY`](https://2.python-requests.org/en/master/community/updates/#id35), [`NO_PROXY`](https://2.python-requests.org/en/master/community/updates/#id81).

(Note that the names of the `*_PROXY` environment variables seems be a [convention](https://superuser.com/questions/944958/are-http-proxy-https-proxy-and-no-proxy-environment-variables-standard).)

To make extra sure we don't miss anything, it would probably be worth cloning the Requests repo and grepping our way using `environment variable`, `os.getenv` and `os.environ.get`.

The scope of this issue is rather broad, so if that's confirmed and as suggested by @sethmlarson in https://github.com/encode/httpx/pull/277#issuecomment-525036637, how about creating issues for each set of environment variables?

**Comment by florimondmanca** [comment]
After inspecting the Requests code base, I updated the list with `CURL_CA_BUNDLE` — I couldn't find any other use of environment variables in there.

**Comment by jlaine** [comment]
Having recently spent a lot of time in wireshark, I'd quite like `SSLKEYLOGFILE` too (unless Python's `ssl` provides this free of charge?)

**Comment by florimondmanca** [comment]
> Having recently spent a lot of time in wireshark, I'd quite like `SSLKEYLOGFILE` too (unless Python's `ssl` provides this free of charge?)

Seems it will be [landing in Python 3.8](https://bugs.python.org/issue34271). Meanwhile, [sslkeylog](https://github.com/segevfiner/sslkeylog)?
