### ISSUE TITLE
Host header contains userinfo component

### ISSUE THREAD

**Issue by sethmlarson** [encode/httpx#391]
`BaseRequest.prepare()` incorrectly sets the default `Host` header to `userinfo@example.com:123` if given the following URL: `http://userinfo@example.com:123`.

We should be removing the userinfo component from the authority before assigning to `Host`.

**Comment by tomchristie** [comment]
Do we want a `URL.host_with_port` property, or something similar?

Are there any prior art examples of URL libraries giving an explicit naming to the host+explicit-port-if-it-exists portion of the authority string?

**Comment by sethmlarson** [comment]
host_with_port sounds more relevant for the CONNECT case.

I've seen "hostname" used for host and port if it's non-default.

**Comment by tomchristie** [comment]
Reviewing [stdlib](https://docs.python.org/3/library/urllib.parse.html), [furl](https://github.com/gruns/furl), [purl](https://github.com/codeinthehole/purl), [hyperlink](https://hyperlink.readthedocs.io/en/latest/index.html), I don't see any prior art (and stdlib uses `hostname` as just the `host` component.)

We might want to switch our `port` property to return an optional port, rather than a port-or-default, which would be helpful here.

Potentially also some thinking to do here wrt. bytewise vs. str representations. Eg. I'm not sure we've completely nailed down some very definitive "this URL property returns an hostname string" vs. "this URL property returns a bytewise encoded hostname".

(In this case we want the plain bytewise representation)

Similarly wrt. path representations and escaping.

**Comment by sethmlarson** [comment]
You're right, was misremembering the stdlib. Totally agree with the port not returning a value via inference and then have a method/property to resolve the port with defaults applied.
