### ISSUE TITLE
Allow Responses to be used as Context Managers

### ISSUE THREAD

**Issue by sethmlarson** [encode/httpx#393]
Requests API allows Responses to be used and closed as a context manager.

We should allow the following use-cases:

```python
async def run_async():
    client = httpx.AsyncClient()
    async with client.get("https://example.com") as resp:
        resp.raise_for_status()

def run_sync():
    client = httpx.Client()
    with client.get("https://example.com") as resp:
        resp.raise_for_status()
```

See: PendragonLore/anido#1

**Comment by florimondmanca** [comment]
I think this is a good thing beyond Requests compatibility — ensures that all resources are properly closed in case something goes wrong. I'm kind of growing the intuition that ideally we should be following trio's lessons and enforce (async) context manager usage *everywhere* — on clients, on responses, …

**Comment by tomchristie** [comment]
Okay, *so*...

This is relevant *only* for the streaming case.
In other cases the response has been closed by the point it's returned from the function.

There's a question here to be had in that `client.get(..., stream=True)` is actually fundamentally different to `client.get(...)` because you *really* want to be using a context manager for the first case.

Requests has exactly the same issue, and actually makes it really easy to *not* close streaming responses. One option that we could do here that's a bit radical would be to diverge from the `requests` API here, even through `stream=True` is a fairly widely used case.

Eg. `client.stream()` could return a context managed response. (It might have a default `method='get'` that could be overidden.)

One other bugbear to be wary of here is that "stream" in this context specifically means "stream the response", not "stream the request" (which yes, we support, but that's different), but the naming isn't very clear about the expectation.

**Comment by gdhameeja** [comment]
I'd like to work on this.

**Comment by tomchristie** [comment]
Main question here is where we want to go with the API...

* Add a `.stream(request='GET')` method which is *always* what we use for streaming cases, so that we can ensure that they're always context-manged.
* Stay in line with `requests` and just use `stream=True` on the existing methods. Keeps the API the same, but really easy to fail to close a response, which isn't *awful* but will leave the connection hanging.

**Comment by sethmlarson** [comment]
Maybe we can put a warning on the Responses garbage collector that it wasn't closed properly, similar to files?

**Comment by jaKass3** [comment]
Idk what to do I’m still learning 
    On Friday, October 4, 2019, 07:09:29 AM CDT, Seth Michael Larson <notifications@github.com> wrote:  
 
 
Maybe we can put a warning on the Responses garbage collector that it wasn't closed properly, similar to files?

**Comment by tomchristie** [comment]
Closing this. Evidentally outdated somewhere along the line - we *do* support responses as context managers. 👍

**Comment by florimondmanca** [comment]
@tomchristie Do we? The `Response` class doesn't implement `__aenter__()`/`__aexit__()`, so this might have been an oversight?

**Comment by tomchristie** [comment]
Obsoleted by #600
