### ISSUE TITLE
Fire and forget / One way requests

### ISSUE THREAD

**Issue by kesavkolla** [encode/httpx#424]
Is there any way to make a POST request but don't wait for the response.  It's similar to Beacon API (https://developer.mozilla.org/en-US/docs/Web/API/Beacon_API) on web.  At times we need to just fire the request and don't wait for the response.

**Comment by florimondmanca** [comment]
Hi, I don’t think we support this yet.

Do you know of other Python HTTP clients that support this already?

**Comment by kesavkolla** [comment]
I was searching for other python libraries too but haven't found any.  I've an use case where the server implementation takes long time as it has to do several things.  The client really doesn't need any response back.

**Comment by tomchristie** [comment]
I don't see us supporting this directly, although you can use `stream=True` so that you're not waiting for the response body.
You'd need to either use threads `Client` or a seperate async task `AsyncClient`, so that you're performing the request without blocking the main program flow.

**Comment by florimondmanca** [comment]
> the server implementation takes long time as it has to do several things.

If you have control on the server, it might be worth seeing whether the non-blocking behavior could be added there instead?

Otherwise as Tom suggested, you can fire up a task to run concurrently to your main program so that reading the response doesn’t block the rest of the execution. This isn’t particular to HTTPX, thigh; there’s an example of how to do this in asyncio [here](https://realpython.com/async-io-python/#using-a-queue).
