### ISSUE TITLE
can't use proxies args with client

### ISSUE THREAD

**Issue by DeemoASCII** [encode/httpx#479]
httpx version: 0.7.5
when I try:
` client =  httpx.AsyncClient() `
` resp = await client.get('http://python.org',proxies={'http':'...'})`
 I got the error like:
`TypeError: get() got an unexpected keyword argument 'proxies'`
but the api doc say:
![image](https://user-images.githubusercontent.com/22360953/66992910-4239ff00-f0fd-11e9-963c-8d19b3ab8ca0.png)
,so what should i do that i can use proxies with one request . ps:' 生气气😡'

**Comment by tomchristie** [comment]
> ps: ' 生气气😡'

Closing this issue out of hand. Not interesting in interacting with folks who don't bring a constructive attitude to their interactions.

The user here isn't being outright offensive, but it's clearly unneccessary.

Note that the client docs here *are* incorrect, since we don't yet support per-request proxies. #464 resolves this particular issue. We should chat about if we're happy for it to go in it's current state or not.

Related: It looks like the `proxies` argument is currently included the top-level API functions, but isn't wired up. We should drop it from there for now.

**Comment by DeemoASCII** [comment]
> > ps: ' 生气气😡'
> 
> Closing this issue out of hand. Not interesting in interacting with folks who don't bring a constructive attitude to their interactions.
> 
> The user here isn't being outright offensive, but it's clearly unneccessary.
> 
> Note that the client docs here _are_ incorrect, since we don't yet support per-request proxies. #464 resolves this particular issue. We should chat about if we're happy for it to go in it's current state or not.
> 
> Related: It looks like the `proxies` argument is currently included the top-level API functions, but isn't wired up. We should drop it from there for now.



> To be absolutely clear @DeemoASCII is still absolutely welcome, but the non-constructive attitude in the comment doesn't have any place here.
> 
> Open source software is a collaborative effort. If you see something that needs fixing, by all means be a part of helping get that fixed. But please do so with the attitude of being a helpful, positive part of a team effort.

I'm so sorry.  
but you may have misunderstood what I meant.
that's just a habit , I want to show a lovely attitude. it's a cultural difference.

other:
I use httpx in my work long time, today i got some bug which is fixed in version >0.7.3, so I update the version, but the proxies can't work, i don't know how to make it work perfectly
