### ISSUE TITLE
Per-request control for proxies

### ISSUE THREAD

**Issue by yeraydiazdiaz** [encode/httpx#486]
Split from https://github.com/encode/httpx/issues/480#issue-508365236

**Comment by tomchristie** [comment]
Not sure *why* I thought it would be a good idea to support per-request control for proxies.
I think we ought to pass on this, and only allow proxy configuration on a per-client basis instead.

**Comment by inikolaev** [comment]
@tomchristie May I ask why is that a bad idea to use per request proxy configuration?

I'm migrating from `requests` and for some endpoints of the API we have to send requests via proxy. With current set up it looks like there's no way to configure proxies per endpoint, only scheme and host are supported, and I'm forced to use a separate client just to make request via proxy.

Same goes for `verify` parameter, even though it's described in the documentation that it's present on request level, but it's not.

**Comment by tomchristie** [comment]
Sure. The answer is that it has an impact on lower-level API too, so...

`httpx` has a very clearly defined transport-level API, that we'll promote to public API for 1.0.
The contract is currently made explicit in the `httpcore` docs, here... https://www.encode.io/httpcore/api/

A single `.request()` method, that issues an HTTP request, and returns an HTTP response.

Now... If we want to *change* the proxy on a per-request basis in `httpx` without impacting the nice clarity of that interface, we *could* do so, but it means mounting a different proxy instance, with it's own separate connection pool. The question then, is, what do we expect the behaviour of that connection pool to be? Are we expecting keep-alive connections to be closed off at the end of that request/response (since it's a single per-request proxy), or keep that connection pool open for the duration of the client lifespan?

The difference here to `requests`/`urllib3` is that they have a shared connection pool that'd additionally keyed by whatever proxy arguments are passed in the request call. That's great but it also means that the low-level "adapter" interface is less narrowly defined. (Which eg. makes it marginally more complex at that level, more awkward to implement alternative transports, or to reason about the expected behaviour at that level.)

So, things we can do instead...

* Ensure that mounting proxies onto particular URLs/hosts is well supported/documented, so that folks can easily see how to setup a client with eg. proxy to X for the default case, and proxy to Y for connections to "example.org". (Perhaps there's a valid issue here to allow only particular path-prefixes too, not sure?)
* *Possibly?* make it easier to clone clients, with a single change, eg. `proxy_client = Client.copy_with(proxy=...)`.

**Comment by inikolaev** [comment]
In my use-case I would expect proxy connections to be alive as long as client lives - while it's only a single endpoint, it would still be used regularly.

I'm not particularly familiar with implementation details for `requests` or `httpx`, but looking at the code now it looks my use-case could be solved by just adding a boolean `proxy` parameter, which would force using proxy for a request. 

In my case proxy doesn't have to be added dynamically, but is there any reason for why it can't be done? What I mean is calling `init_proxy_dispatch` and adding it to `proxies` map in the client?

Making a copy of a client is not really an issue for me, at least for now I would need to create a separate client for proxy connections. I have a higher-level HTTP client abstraction, which allows me to expose interface with boolean `proxy` parameter and the route requests between different `httpx` clients.

One thing I've been missing in many HTTP clients is the lack of monitoring support. It probably deserves a separate issue though, but in short it would be nice to collect different statistics about requests, connection pools, DNS resolution time, connection time (TCP and TLS), timeouts to name a few. Or provide an API to make it easier for different vendors to hook into.
