### ISSUE TITLE
Any explicit `Content-Type` header should take precedence over the encoding default.

### ISSUE THREAD

**Issue by daxartio** [encode/httpx#620]
https://github.com/encode/httpx/blob/eba29da632c3a0fce55a54fc18cd6b147db43726/httpx/models.py#L643

I send json argument and content type when i do request, but my content type is replacing to "application/json". I think it is bug

**Comment by florimondmanca** [comment]
Hi @daxartio,

What exact use case are you facing that requires passing `json=...` while setting a `Content-Type` to something else than `application/json`?

As a workaround, using `data=...` should allow you to set the `Content-Type` yourself:

```python
data: bytes = serialize(some_dict)
r = await httpx.post(url, data=data, headers={"content-type": "application/x-myformat"})
```

**Comment by tomchristie** [comment]
Sure thing.

We shouold probably change this...

https://github.com/encode/httpx/blob/eba29da632c3a0fce55a54fc18cd6b147db43726/httpx/models.py#L627

To `self.headers.setdefault('Content-Type', content_type)`, so that if the user has *explicitly* set a Content-Type header that takes precedence.

(Or else leave that line as it is an use `if content_type and 'Content-Type' not in self.headers` in the previous line.)

Pull requests accepted.
