### ISSUE TITLE
print(error) doesn't print anything

### ISSUE THREAD

**Issue by AlJohri** [encode/httpx#683]
I tried printing in an f-string and also an independent `print(e)` and both didn't result in any output.

sample code where I noticed the issue:
```python
        try:
            response = await httpx.post(
                CORENLP_SERVER,
                params={"properties": json.dumps(properties)},
                data=text.strip(),
                headers={'Content-Type': 'text/plain; charset=utf-8'}
            )
        except httpx.exceptions.ReadTimeout as e:
            print(e)
            print(f'ERROR: {str(e)}')
            print(repr(text[0:50]))
            return []
```

**Comment by kousikmitra** [comment]
In the connection backend where the exception is being raise there the exception object doesn't have any message initialized that's why your code isn't printing any error message.

**asyncio backend**
https://github.com/encode/httpx/blob/f3b799912ede54b2f500c47d5f8a59a010d6b2ff/httpx/backends/asyncio.py#L203-L204

https://github.com/encode/httpx/blob/f3b799912ede54b2f500c47d5f8a59a010d6b2ff/httpx/backends/asyncio.py#L224-L225

**trio backend**

https://github.com/encode/httpx/blob/f3b799912ede54b2f500c47d5f8a59a010d6b2ff/httpx/backends/trio.py#L102

https://github.com/encode/httpx/blob/f3b799912ede54b2f500c47d5f8a59a010d6b2ff/httpx/backends/trio.py#L120

**Comment by florimondmanca** [comment]
FWIW printing the `repr` form of the exception should show the exception class as well. You can achieve this with the `!r` specifier:

```python
print(f'ERROR: {e!r}')
```

But we may want to tweak our exceptions so that `str()` always outputs something meaningful, yes.

**Comment by AlJohri** [comment]
Ah, you're right- I didn't realize that python exceptions by default only print the message. I've been using `print(e)` for so long and always got _SOME_ result so I thought something was going wrong.

```python
try:
	raise ValueError()
except Exception as e:
	print(e)
```

Even requests exceptions have the same behavior.

```
import traceback
import requests

try:
	requests.get("thiswebsitedoesnotexit")
except requests.exceptions.MissingSchema as e:
	print(e)
```

It's probably fine to keep `str` behavior it as is since that's what's widely practiced with exceptions. If anything, adding a message when raising the `ConnectTimeout` couldn't hurt.
