### ISSUE TITLE
how PoolLimits soft and hard limits work?

### ISSUE THREAD

**Issue by dmfigol** [encode/httpx#708]
Sorry, I couldn't find this anywhere.
Do you mind explaining what soft and hard limits actually do?
```
pool_limits = httpx.PoolLimits(soft_limit=20, hard_limit=100)
client = httpx.AsyncClient(pool_limits)
```
Thank you!

**Comment by tomchristie** [comment]
@dmfigol - How's this?... https://github.com/encode/httpx/pull/712/files

**Comment by dmfigol** [comment]
@tomchristie this is helpful, thank you!
Could you provide a little bit more details, what is the expected behavior when soft limit and hard limit are reached?
If I understood correctly hard limit is implemented with semaphore and we will be just waiting for an existing connection to be released, but I have no idea about the soft one.

**Comment by tomchristie** [comment]
Closing this in favour of #787.

> what is the expected behavior when soft limit and hard limit are reached?

* soft_limit reached: when a connection is closed, it gets fully closed, rather than staying in a keep-alive state for a bit.
* hard_limit reached: cannot establish more connections than this limit. Attempts to make a new connection will wait until the configured pool timeout, and error if connection is made available within that time.
