### ISSUE TITLE
Provide more fine grained timing information

### ISSUE THREAD

**Issue by ulope** [encode/httpx#775]
Currently httpx only provides the requests equivalent `.elapsed` property on `Response` objects.

It would be very useful if more fine grained timing information would be available.
From working with curl the following have been helpful:
- name resolution
- tcp connected
- protocol connected (e.g. TLS done)
- request last byte sent
- response first byte arrived
- total (e.g. what `.elapsed` is now)

Of course this all becomes a bit more complicated with pooled connections, keep-alive, http2, etc.

**Comment by florimondmanca** [comment]
Interesting... Can you show how to enable those metrics on curl, and what the output looks like?

**Comment by ulope** [comment]
Sure.
You can get them via the `-w` format flag.

For example:
```shell
curl -s -o /dev/null https://google.com -w '
  namelookup: %{time_namelookup}
  connect: %{time_connect}
  appconnect: %{time_appconnect}
  pretransfer: %{time_pretransfer}
  redirect: %{time_redirect}
  starttransfer: %{time_starttransfer}
  total: %{time_total}\n'
```

```
  namelookup: 0.004395
  connect: 0.507033
  appconnect: 0.568980
  pretransfer: 0.569242
  redirect: 0.000000
  starttransfer: 0.683912
  total: 0.684036
```

**Comment by florimondmanca** [comment]
@ulope Thanks for the extra details!

I'm not sure we're going to want to treat this as in-scope for now… It would probably be a nice-to-have, but my guess is that this *could* be better-served by a third-party package that would use a coroutine-aware profiling library such as [yappi](https://github.com/sumerc/yappi) to place profiling checkpoints on the relevant methods.

I'm not absolutely against it, but since I don't think Requests has any metrics of this sort, we should probably push back for having this in core at least until we reach 1.0…

**Comment by tomchristie** [comment]
> I'm not against it in principle, but since I don't think Requests has any metrics of this sort, we should probably push back for having this in core at least until we reach 1.0…

Yup, seems reasonable to me.

Not to say that we might not want to address this at some point, but it's probably worth keeping out of scope for now.

> my guess is that this could be better-served by a third-party package that would use a coroutine-aware profiling library such as yappi to place profiling checkpoints on the relevant methods.

`yappi` looks really neat - thanks for that!
