### ISSUE TITLE
httpx.Request don't take the same arguments

### ISSUE THREAD

**Issue by L0ric0** [encode/httpx#794]
the `httpx.Request` takes `(method, url, [params], [data], [json], [headers], [cookies])`
and the `requests.Request` takes `(method=None, url=None, headers=None, files=None, data={}, params={}, auth=None, cookies=None, hooks=None)`

this should be pointed out in the documentation or implemented

**Comment by florimondmanca** [comment]
Happy to review any PRs that document which parameters aren’t present on our `Request` class compared to Requests. :)

From what I can see these are:

- `files` (I believe this is handled via `data`, isn’t it?)
- `hooks`

**Comment by StephenBrown2** [comment]
`files` is there, but `auth` isn't.
https://github.com/encode/httpx/blob/82dc6f32f864d26677df8fc61249a7fc74c687e8/httpx/_models.py#L591-L604

However, `auth` is available on the `request` method: https://github.com/encode/httpx/blob/82dc6f32f864d26677df8fc61249a7fc74c687e8/httpx/_api.py#L18-L34

Hooks are discussed here: https://github.com/encode/httpx/issues/790

**Comment by florimondmanca** [comment]
> but `auth` isn't

Not immediately obvious to me that this is a deliberate design choice, or just the way things ended up being implemented. As a matter of fact, we do support per-request auth, so… Maybe there's room for retro-fitting to the Requests API here?

**Comment by tomchristie** [comment]
> Not immediately obvious to me that this was a deliberate design choice, or just the way things ended up being implemented. (We're passing auth in Client.send(), but we probably could very well move it onto a request.auth attribute.) As a matter of fact, we do support per-request auth, so… Maybe there's room for retro-fitting to the Requests API here?

I think we proabably want to keep things as they are. When I started out the "Requests Compatability" the intention was to document anything that differed across the Basic and Advanced usage guides, rather than that lower level bits of API would match all the way through.

It makes sense to me that our `auth` parameter would be on the `send()` method, since it's *not* something that we can always just call into to build some extra headers on the request method, it actually alters the sending flow.

I think we might be okay with a slightly general "Not all stuff in the lower level bits of API might match up exactly", giving a couple of examples? Or else perhaps a section for low level API differences, where we briefly list any notable cases. (Eg. I also haven't reviewed how our `build_request`/`send` compares to the `requests` equivelent.)

**Comment by StephenBrown2** [comment]
Agreed, I think it was only top-level compatibility (`httpx.HTTP_VERB`) that was shot for, and other things have come along naturally as they made sense to include.

**Comment by Pradhvan** [comment]
@florimondmanca hey, you should close this PR as #823 is already been merged. 😄

**Comment by florimondmanca** [comment]
Thanks for the heads up @Pradhvan!
