### ISSUE TITLE
Can't read response in Auth.auth_flow

### ISSUE THREAD

**Issue by georgek** [encode/httpx#802]
I want to implement auto-refreshing of a token but in order to get the new token I need to be able to read the server response in the custom auth_flow method.

It seems like a trivial change to get the client to `read()` or `aread()` the response before sending it back (like it does with the request), and things actually seem to work fine, but some tests break which I don't understand so wanted to check that I'm not doing completely the wrong thing here.

**Comment by florimondmanca** [comment]
Hi!

I assume you’d like to access the response body because the server returns an auth token as a JSON payload, eg `{"token": "123abc"}`, right?

Being able to access the request body is documented at the end of [Customizing Authentication](https://www.python-httpx.org/advanced/#customizing-authentication), but we don’t have such a flag for responses yet.

Sounds like a sensible symmetric addition to me, though! Want to throw a PR together to see what it would look like? :)

**Comment by tomchristie** [comment]
Indeed, adding a `requires_response_body` attribute would make sense.

**Comment by georgek** [comment]
OK, great! I'll have a go at it today.
