### ISSUE TITLE
Multipart Data Types - Requests Compatibility Delta

### ISSUE THREAD

**Issue by eric-spitler** [encode/httpx#808]
For multipart file uploads with additional data (supplying **`data=my_dict, files=my_files_dict`**) results in different behavior than the Requests API.

In Requests, when it encodes the key/value pairs from the `data` dict, it also restricts to `str`|`bytes` value data types, but will always execute `str(value)` if not an instance of `bytes`:
https://github.com/psf/requests/blob/master/requests/models.py#L134..L135

In HTTPX, this raises a `ValueError` rather than cast to `str` when instantiating the `DataField` object for each key/value pair:
https://github.com/encode/httpx/blob/82dc6f32f864d26677df8fc61249a7fc74c687e8/httpx/_content_streams.py#L205..L208

Obviously, this is an easy fix on the application side - just convert all values to `str` if needed. Is this an intended deviation from the Requests API?

**Comment by tomchristie** [comment]
Well, that depends.

Were we being intentionally more specfic here? Yup. We've got tight type specifications all the way through, and it's fairly reasonable to strictly enforce "you need to pass the right type here".

As soon as you start allowing folks to pass arbitrary objects we'll likely end up getting requests like "dates should be formatted like X", "timedeltas should be formatted like Y", where actually the expected behavior may be pretty underdefined, so it's not a bad idea to strictly enforce "this thing is going to be a string, so for arbitrary objects the end user needs to be responsible for how they want to format that object into a string".

On the other hand, being liberal to a little bit of "you can pass any str-able object here" is a more relaxed approach, that'd be more closely in line with requests.

Out of interest, what kind of datatype were you passing when you ran into the difference in behavior?

**Comment by eric-spitler** [comment]
In my case last night, it was an integer.

Totally understand where you're coming from with things like datetime objects - formatting is use case specific. Even float objects can have formatting requirements such as number of decimal places.

I'm okay keeping this as-is; was more about indicating that if the intention was being "requests-compatible" then this was a break from that.

**Comment by florimondmanca** [comment]
Going to close this as I think the original question on motivation for this behavior has been answered. :-)
