### ISSUE TITLE
Sync client fails on ASGI apps with unhelpful traceback

### ISSUE THREAD

**Issue by Singletoned** [encode/httpx#879]
I tried using httpx with with an ASGI app in the way that was implied by the docs.  It throws an error that feels like a problem with httpx, as FastAPI is currently being used in production in other ways.  If you confirm that this is a bug in httpx, I'm willing (and probably capable) to fix it and submit a patch.

```
import httpx
from fastapi import FastAPI

app = FastAPI()


@app.get("/users/{user_id}")
async def read_user(user_id: str):
    return {'user_id': user_id}

with httpx.Client(app=app) as client:
    response = client.get("http://www.example.com/users/foo")
```

Throws the error:
```
Traceback (most recent call last):
  File "temp.py", line 12, in <module>
    response = client.get("http://www.example.com/users/foo")
  File "/Users/singletoned/.envs/testino/lib/python3.7/site-packages/httpx/_client.py", line 714, in get
    timeout=timeout,
  File "/Users/singletoned/.envs/testino/lib/python3.7/site-packages/httpx/_client.py", line 571, in request
    request, auth=auth, allow_redirects=allow_redirects, timeout=timeout,
  File "/Users/singletoned/.envs/testino/lib/python3.7/site-packages/httpx/_client.py", line 591, in send
    request, auth=auth, timeout=timeout, allow_redirects=allow_redirects,
  File "/Users/singletoned/.envs/testino/lib/python3.7/site-packages/httpx/_client.py", line 618, in send_handling_redirects
    request, auth=auth, timeout=timeout, history=history
  File "/Users/singletoned/.envs/testino/lib/python3.7/site-packages/httpx/_client.py", line 654, in send_handling_auth
    response = self.send_single_request(request, timeout)
  File "/Users/singletoned/.envs/testino/lib/python3.7/site-packages/httpx/_client.py", line 678, in send_single_request
    response = dispatcher.send(request, timeout=timeout)
  File "/Users/singletoned/.envs/testino/lib/python3.7/site-packages/httpx/_dispatch/wsgi.py", line 90, in send
    result = self.app(environ, start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
```

**Comment by florimondmanca** [comment]
Hi Ed!

This is actually expected behavior. You’re trying to use an ASGI app with the sync client — this is not supported as the sync client only supports WSGI.

So you should use an AsyncClient with your FastAPI app. :)

I have personally got bitten by this in the past too, so we should probably do something to improve the UX here. Maybe checking the signature of `app` in `WSGIDispatcher, and raising à helpful error message if it doesn’t look like a WSGI app (ie à callable with 2 parameters).

**Comment by florimondmanca** [comment]
I went ahead and updated the issue description.

Note that we don’t want to support calling async apps from the sync client (eg running the app in a new event loop) because this kind of bridging approach has bitten us in the past. We should encourage a strict separation of use cases (which is why `app` on the sync Client must be WSGI, while on the async client it must be ASGI).

**Comment by Singletoned** [comment]
Thanks for the quick response on this. 

The docstring for the sync Client was wrong (which was what confused me), so I've updated it.  Also the API of the AsyncClient wasn't in the docs.  I've put it on the API page, but I see arguments for putting it somewhere else (I can't really see arguments for not having it up at all).  If the AsyncClient had been on that page, I'd probably have guessed what the error was.
