### ISSUE TITLE
Should `Headers.keys` be a set-like keys view?

### ISSUE THREAD

**Issue by obataku** [encode/httpx#899]
### Checklist

- [X] I searched the [HTTPX documentation](https://www.python-httpx.org) but couldn't find what I'm looking for.
- [X] I looked through similar issues on GitHub, but didn't find anything.
- [ ] I looked up "How to do ... in HTTPX" on a search engine and didn't find any information.
- [ ] I asked the [community chat](https://gitter.im/encode/community) for help but didn't get an answer.

### Question

presently [`Headers.keys`](https://github.com/encode/httpx/blob/master/httpx/_models.py#L458) returns a `typing.List[str]` rather than a (set-like) `typing.KeysView[str]`, which appears to violate the `Mapping` protocol: https://docs.python.org/3/library/collections.abc.html#collections.abc.KeysView

this breaks code that expects set-like operations with `Headers.keys`, e.g.
```
    dst: Dict[str, str] = ...
    headers: httpx.Headers = ...
    keys: Set[str] = {"set-cookie", "set-cookie2"}
    dst.update({k: headers[k] for k in keys & headers.keys()})
```

is this an intentional design choice or simply an oversight?

**Comment by florimondmanca** [comment]
Not necessarily intentional, no. Any idea how we could return such a keyview object? I don't know how we can construct one from something that's not a dict.

**Comment by florimondmanca** [comment]
Okay I found it — we can use `typing.KeysView(<dict>)`, `typing.ValuesView(<dict>)`, etc.

Thinking about this more, I think this was an intentional choice, basically to keep the scope down a bit.

Eg one reason why we cannot very easily implement these interfaces (eg building a dict and returning the result of calling `.keys()` on it) is because duplicate headers are not forbidden by the HTTP spec. `Set-Cookie` is a prime example of this.

That doesn't mean we can't implement the `KeysView`/`ValuesView`/`ItemsView` protocols, though, but we'd need to implement our own subclasses, and basically end up with [what `multidict` is doing](https://github.com/aio-libs/multidict/blob/master/multidict/_multidict_py.py). Making that work with type hints etc would be a significant chunk of code and work.

Don't think we're ready to make that move yet… But I'd be interested to see what making this work would take us.

**Comment by obataku** [comment]
I think the easiest way would likely be something similar to how aiolibs `multidict` does it, yeah; using the default `KeysView`, `ValuesView` wouldn't work well for the reasons you mention although it's worth pointing out that the `XView` constructors accept general mappings (and using stale `dict` snapshots to implement the views would violate the protocol anyway).

**Comment by florimondmanca** [comment]
So, switching to `multidict` is not as simple unfortunately, because we already have some subtle behavior differences between our `QueryParams` and `Headers` models, and how multidict behaves.

Eg currently `params[key]` returns the first value in the list of items for `key`, while `multidict` returns the last.

It's unfortunate, and maybe we should have used `multidict` from the start, but these differences mean it's just not very easy to switch to `multidict`.

Maybe this is one item we should think through this before 1.0 lands. cc @tomchristie
