### ISSUE TITLE
Release timeline

### ISSUE THREAD

**Issue by achapkowski** [encode/httpx#912]
Hello,

What is the new timeline for the v1.0.0 release?  It's past April 2020 and the API is still at v0.12.1.  

Thank you

```A 1.0 release is expected to be issued sometime on or before April 2020.```

**Comment by florimondmanca** [comment]
Hi,

I’d be interested in Tom’s answer to, but I guess it’s fair to say that things got a bit delayed on the HTTPX side due to all that’s been going on in the world in the past couple of months - priorities shift. The April deadline is probably effectively delayed to later this year, but I personally don’t know when.

FWIW we should be releasing 0.13 fairly soon with a new sync backend implementation, but I think there are still a couple of items we’d need to tackle before 1.0.

Eg deciding on the right API surface for type hints, reviewing proxy modes, and some other items.

Nothing absolutely major from my POV - the user-side high level and client APIs are mostly rounded - but we should take our time to review things properly and get some more usage feedback once 0.13 is out.

**Comment by achapkowski** [comment]
@florimondmanca thanks for this response!  I figured that's why things got delayed.  I like this API because it seems like such a great progression from requests to httpx.  I want to explore it's integration into an API we use so have the async support, but there is no way I can use it until it goes to v1.x.

**Comment by achapkowski** [comment]
@tomchristie does that mean @florimondmanca response is the correct timeline?

**Comment by tomchristie** [comment]
I think "when it's ready" is fine. I oughta put some more time into helping get 0.13 over the line since that's pretty much our 1.0 pre-release.

Would certainly *have been* pushing to have it ready for PyCon in other circumstances, but here we are. We oughta drop that text for starters.

**Comment by tomchristie** [comment]
"Summer 2020?"

**Comment by yeraydiazdiaz** [comment]
@achapkowski:

> but there is no way I can use it until it goes to v1.x.

Why is that?

**Comment by achapkowski** [comment]
@yeraydiazdiaz because it's listed as alpha software and companies do not like to build around alpha software. Not my call
