### ISSUE TITLE
AsyncClient set timeout but doesn't work?

### ISSUE THREAD

**Issue by zszjszlk2** [encode/httpx#961]
![stop](https://user-images.githubusercontent.com/46711557/82195451-e6518600-992a-11ea-8e97-29ea3bed9edd.png)
![running](https://user-images.githubusercontent.com/46711557/82195463-e94c7680-992a-11ea-8439-03f53d842007.png)
Help!Any problems about my codes or httpx's problem?
How to fix it?

**Comment by tomchristie** [comment]
Hi there, thanks for getting involved. 😃

I'm closing this off for now, since we're moving to a "maintainer driven" policy on our issue tracker & pull request spaces. This will gradually help us ensure that these spaces do a good job of properly reflecting the ongoing project priorities.

The best places to start with this are instead [the chat room](https://gitter.im/encode/community), or [the discussion group](https://discuss.encode.io/).

Many thanks. 💛✨

[Read more about our contribution guidelines.](https://github.com/encode/.github/blob/master/CONTRIBUTING.md)
